// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $.miniDropdown = function(element, options) {
      var animate, animateMethods, getSubNav, hide, hideAll, setState, show,
        _this = this;
      this.defaults = {
        activeClass: "active",
        animation: "basic",
        easing: "swing",
        show: 0,
        hide: 0,
        delayIn: 0,
        delayOut: 0,
        showFunc: null,
        hideFunc: null
      };
      animateMethods = {
        basic: {
          show: "show",
          hide: "hide"
        },
        fade: {
          show: "fadeIn",
          hide: "fadeOut"
        },
        slide: {
          show: "slideDown",
          hide: "slideUp"
        }
      };
      this.state = '';
      this.settings = {};
      this.$element = $(element);
      animate = function($subnav, type) {
        $subnav.stop(false, true);
        return $subnav[animateMethods[_this.settings.animation][type]](_this.settings[type], _this.settings.easing, function() {
          return $(this)[type]();
        });
      };
      show = function($item, $subnav) {
        hideAll($item);
        $item.children("a").addClass(_this.settings.activeClass);
        window.clearTimeout($item.data("timeoutId"));
        console.log(_this.settings.delayIn);
        return $item.data("timeoutId", window.setTimeout(function() {
          return animate($subnav, "show");
        }, _this.settings.delayIn));
      };
      hide = function($item, $subnav) {
        $item.children("a").removeClass(_this.settings.activeClass);
        window.clearTimeout($item.data("timeoutId"));
        return $item.data("timeoutId", window.setTimeout(function() {
          return animate($subnav, "hide");
        }, _this.settings.delayOut));
      };
      getSubNav = function($link) {
        return $link.children("ul").first();
      };
      hideAll = function($item) {
        _this.$links.removeClass(_this.settings.activeClass);
        return _this.$subnavs.stop(false, true).hide();
      };
      setState = function(state) {
        this.state = state;
      };
      this.getState = function() {
        return state;
      };
      this.getSetting = function(settingKey) {
        return this.settings[settingKey];
      };
      this.callSettingFunction = function(functionName) {
        return this.settings[functionName]();
      };
      this.init = function() {
        var hasEasingFunc, self,
          _this = this;
        this.settings = $.extend({}, this.defaults, options);
        self = this;
        this.$items = this.$element.children("li");
        this.$links = this.$items.children("a");
        this.$subnavs = this.$items.children("ul");
        hasEasingFunc = $.isFunction($.easing[this.settings.easing]);
        if (!hasEasingFunc) {
          this.settings.easing = "swing";
        }
        return this.$items.bind({
          mouseenter: function(e) {
            var $item, $subnav, fn;
            $item = $(e.currentTarget);
            $subnav = getSubNav($item);
            fn = ($.isFunction(_this.settings.showFunc) ? _this.settings.showFunc : show);
            return fn.apply(self, [$item, $subnav]);
          },
          mouseleave: function(e) {
            var $item, $subnav, fn;
            $item = $(e.currentTarget);
            $subnav = getSubNav($item);
            fn = ($.isFunction(_this.settings.hideFunc) ? _this.settings.hideFunc : hide);
            return fn.apply(self, [$item, $subnav]);
          }
        });
      };
      return this.init();
    };
    return $.fn.miniDropdown = function(options) {
      return this.each(function() {
        var miniDropdown;
        if (void 0 === ($(this)).data('miniDropdown')) {
          miniDropdown = new $.miniDropdown(this, options);
          return ($(this)).data('miniDropdown', miniDropdown);
        }
      });
    };
  });

}).call(this);
